spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm
    username: root
    password: 88888888
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
mybatis:
#  config-location: classpath:/mapper/*.xml
  type-aliases-package: cn.lulucar.element.entity
  
server:
  # 服务端口
  port: 8888
